import type { BuildsService } from "@/services/builds";
import * as z from "zod/v4";
import {
  CancelBuildToolInputSchema,
  CancelBuildToolOutputSchema,
  ExportBuildToolInputSchema,
  ExportBuildToolOutputSchema,
  GetBuildConfigurationsInputSchema,
  GetBuildConfigurationsOutputSchema,
  GetBuildDestinationsInputSchema,
  GetBuildDestinationsOutputSchema,
  GetBuildInputSchema,
  GetBuildOutputSchema,
  GetBuildsInputSchema,
  GetBuildsOutputSchema,
  RunBuildToolInputSchema,
  RunBuildToolOutputSchema,
  StartBuildToolInputSchema,
  StartBuildToolOutputSchema,
} from "@/services/builds";

import {
  DESTRUCTIVE_ANNOTATIONS,
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  defineTool,
  type BuiltInToolGroup,
} from "../builtin-tools";
import { serviceTool } from "./service-tool";

export function createBuildToolGroup(builds: BuildsService): BuiltInToolGroup {
  return {
    id: "builtin:builds",
    name: "Builds",
    children: [],
    tools: [
      defineTool({
        name: "get_builds",
        title: "Get builds",
        description: "List immutable iOS build records.",
        inputSchema: GetBuildsInputSchema,
        outputSchema: GetBuildsOutputSchema,
        annotations: READ_ONLY_ANNOTATIONS,
        handler: async (input) => {
          const page = await builds.builds(input);
          return { builds: page.items, nextCursor: page.nextCursor };
        },
      }),
      defineTool({
        name: "get_build",
        title: "Get build",
        description: "Get a build with sanitized logs.",
        inputSchema: GetBuildInputSchema,
        outputSchema: GetBuildOutputSchema,
        annotations: READ_ONLY_ANNOTATIONS,
        handler: async ({ buildId, afterLogId, logLimit }) => {
          const build = await builds.getBuild(buildId);
          if (!build) throw new Error("Build not found");
          return {
            build,
            logs: await builds.logChunks(buildId, afterLogId, logLimit),
          };
        },
      }),
      defineTool({
        name: "get_build_configurations",
        title: "Get build configurations",
        description: "List build configurations for a worktree.",
        inputSchema: GetBuildConfigurationsInputSchema,
        outputSchema: GetBuildConfigurationsOutputSchema,
        annotations: READ_ONLY_ANNOTATIONS,
        handler: async ({ worktreeId }) => ({
          project: await builds.projectForWorktree(worktreeId),
        }),
      }),
      defineTool({
        name: "get_build_destinations",
        title: "Get build destinations",
        description: "Inspect compatible build destinations.",
        inputSchema: GetBuildDestinationsInputSchema,
        outputSchema: GetBuildDestinationsOutputSchema,
        annotations: READ_ONLY_ANNOTATIONS,
        handler: async (input) => ({
          destinations:
            "buildId" in input
              ? await builds.destinationsForBuild(
                  input.buildId,
                  input.requestId,
                )
              : await builds.destinations(input as never),
        }),
      }),
      defineTool({
        name: "start_build",
        title: "Start build",
        description: "Queue an iOS build.",
        inputSchema: StartBuildToolInputSchema,
        outputSchema: StartBuildToolOutputSchema,
        annotations: WRITE_ANNOTATIONS,
        handler: async (input) => ({
          build: await builds.startBuild(input as never),
        }),
      }),
      defineTool({
        name: "cancel_build",
        title: "Cancel build",
        description: "Cancel an active build.",
        inputSchema: CancelBuildToolInputSchema,
        outputSchema: CancelBuildToolOutputSchema,
        annotations: DESTRUCTIVE_ANNOTATIONS,
        handler: async ({ buildId }) => ({
          build: await builds.cancelBuild(buildId),
        }),
      }),
      defineTool({
        name: "run_build",
        title: "Run build",
        description: "Install and launch without rebuilding.",
        inputSchema: RunBuildToolInputSchema,
        outputSchema: RunBuildToolOutputSchema,
        annotations: WRITE_ANNOTATIONS,
        handler: async (input) => ({
          deployments: await builds.runBuild(input),
        }),
      }),
      defineTool({
        name: "export_build_archive",
        title: "Export build archive",
        description: "Export an archive to a local IPA folder.",
        inputSchema: ExportBuildToolInputSchema,
        outputSchema: ExportBuildToolOutputSchema,
        annotations: WRITE_ANNOTATIONS,
        handler: async (input) => ({
          export: await builds.exportArchive(input),
        }),
      }),
      serviceTool({
        name: "get_build_project",
        title: "Get build project",
        description: "Get the iOS build project configured for a codebase.",
        inputSchema: z.object({ codebaseId: z.string().min(1) }),
        service: builds,
        method: "project",
        arguments: ({ codebaseId }) => [codebaseId],
        resultKey: "project",
      }),
      serviceTool({
        name: "create_build_project",
        title: "Create build project",
        description: "Create an iOS build project for a codebase.",
        inputSchema: z.object({ codebaseId: z.string().min(1) }),
        service: builds,
        method: "createProject",
        arguments: ({ codebaseId }) => [codebaseId],
        resultKey: "project",
        annotations: { ...WRITE_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "save_build_configuration",
        title: "Save build configuration",
        description: "Create or update an iOS build configuration.",
        inputSchema: z.object({ input: z.record(z.string(), z.unknown()) }),
        service: builds,
        method: "saveConfiguration",
        arguments: ({ input }) => [input],
        resultKey: "configuration",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "delete_build_configuration",
        title: "Delete build configuration",
        description: "Delete an iOS build configuration.",
        inputSchema: z.object({ id: z.string().min(1) }),
        service: builds,
        method: "deleteConfiguration",
        arguments: ({ id }) => [id],
        resultKey: "deleted",
        annotations: DESTRUCTIVE_ANNOTATIONS,
      }),
      serviceTool({
        name: "discover_build_sources",
        title: "Discover build sources",
        description: "Discover Xcode projects and workspaces in a worktree.",
        inputSchema: z.object({
          worktreeId: z.string().min(1),
          requestId: z.string().min(1),
        }),
        service: builds,
        method: "discoverSources",
        arguments: (value) => [value.worktreeId, value.requestId],
        resultKey: "sources",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "inspect_build_source",
        title: "Inspect build source",
        description:
          "Inspect schemes, configurations, and targets for an Xcode source.",
        inputSchema: z.object({ input: z.record(z.string(), z.unknown()) }),
        service: builds,
        method: "inspectSource",
        arguments: ({ input }) => [input],
        resultKey: "inspection",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_build_scripts",
        title: "Get build scripts",
        description: "List reusable build scripts.",
        inputSchema: z.object({}),
        service: builds,
        method: "scripts",
        arguments: () => [],
        resultKey: "scripts",
      }),
      serviceTool({
        name: "save_build_script",
        title: "Save build script",
        description: "Create or update a reusable build script.",
        inputSchema: z.object({ input: z.record(z.string(), z.unknown()) }),
        service: builds,
        method: "saveScript",
        arguments: ({ input }) => [input],
        resultKey: "script",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "delete_build_script",
        title: "Delete build script",
        description: "Delete a reusable build script.",
        inputSchema: z.object({ id: z.string().min(1) }),
        service: builds,
        method: "deleteScript",
        arguments: ({ id }) => [id],
        resultKey: "deleted",
        annotations: DESTRUCTIVE_ANNOTATIONS,
      }),
      serviceTool({
        name: "rebuild_build",
        title: "Rebuild build",
        description: "Queue a new build from an existing build snapshot.",
        inputSchema: z.object({
          buildId: z.string().min(1),
          requestId: z.string().min(1),
        }),
        service: builds,
        method: "rebuildBuild",
        arguments: (value) => [value.buildId, value.requestId, null],
        resultKey: "build",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "delete_builds",
        title: "Delete builds",
        description:
          "Permanently delete build records and their retained data.",
        inputSchema: z.object({ ids: z.array(z.string().min(1)).min(1) }),
        service: builds,
        method: "deleteBuilds",
        arguments: ({ ids }) => [ids],
        resultKey: "count",
        annotations: DESTRUCTIVE_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_build_reports",
        title: "Get build reports",
        description: "Get parsed test and coverage reports for a build.",
        inputSchema: z.object({ buildId: z.string().min(1) }),
        service: builds,
        method: "reportsForBuild",
        arguments: ({ buildId }) => [buildId],
        resultKey: "reports",
      }),
      serviceTool({
        name: "generate_build_report",
        title: "Generate build report",
        description: "Generate a parsed test-results or code-coverage report.",
        inputSchema: z.object({
          buildId: z.string().min(1),
          kind: z.enum(["TEST_RESULTS", "CODE_COVERAGE"]),
          requestId: z.string().min(1),
        }),
        service: builds,
        method: "generateReport",
        arguments: (value) => [value.buildId, value.kind, value.requestId],
        resultKey: "report",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "start_worktree_coverage",
        title: "Start worktree coverage",
        description: "Start the configured coverage workflow for a worktree.",
        inputSchema: z.object({ input: z.record(z.string(), z.unknown()) }),
        service: builds,
        method: "startWorktreeCoverage",
        arguments: ({ input }) => [input],
        resultKey: "build",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_worktree_coverage",
        title: "Get worktree coverage",
        description: "Get coverage history for a worktree.",
        inputSchema: z.object({ worktreeId: z.string().min(1) }),
        service: builds,
        method: "coverageHistory",
        arguments: ({ worktreeId }) => [worktreeId],
        resultKey: "history",
      }),
    ],
  };
}
