import * as z from "zod/v4";

import type { GitHubService } from "@/services/github";

import {
  READ_ONLY_EXTERNAL_ANNOTATIONS,
  WRITE_EXTERNAL_ANNOTATIONS,
  type BuiltInToolGroup,
} from "../builtin-tools";
import { serviceTool } from "./service-tool";

const source = "WORKFLOW_AUTOMATION";
const audit = { actor: "workflow", ipAddress: null };
const repositoryPullRequest = z.object({
  owner: z.string().min(1),
  name: z.string().min(1),
  number: z.number().int().positive(),
});

export function createGitHubToolGroup(
  service: GitHubService,
): BuiltInToolGroup {
  return {
    id: "builtin:github",
    name: "GitHub",
    children: [],
    tools: [
      serviceTool({
        name: "get_github_status",
        title: "Get GitHub status",
        description:
          "Test the configured GitHub connection without exposing credentials.",
        inputSchema: z.object({}),
        service,
        method: "testConnection",
        arguments: () => [],
        resultKey: "status",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_github_repositories",
        title: "Get GitHub repositories",
        description: "List configured GitHub repositories.",
        inputSchema: z.object({}),
        service,
        method: "listRepositories",
        arguments: () => [],
        resultKey: "repositories",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_pull_requests",
        title: "Get pull requests",
        description:
          "List GitHub pull requests by scope, repository, and state.",
        inputSchema: z.object({
          scope: z.enum(["MINE", "REVIEW_REQUESTED", "REPOSITORY"]),
          repositoryId: z.string().nullable().optional(),
          state: z.enum(["ALL", "OPEN", "CLOSED", "MERGED"]).default("OPEN"),
          first: z.number().int().min(1).max(100).default(25),
          after: z.string().nullable().optional(),
          includePipelineJobs: z.boolean().default(false),
        }),
        service,
        method: "pullRequests",
        arguments: (value) => [
          value.scope,
          value.repositoryId,
          {
            includePipelineJobs: value.includePipelineJobs,
            state: value.state,
            first: value.first,
            after: value.after,
            requestSource: source,
          },
        ],
        resultKey: "page",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_pull_request",
        title: "Get pull request",
        description: "Get a GitHub pull request by repository and number.",
        inputSchema: repositoryPullRequest,
        service,
        method: "pullRequest",
        arguments: (value) => [value.owner, value.name, value.number, source],
        resultKey: "pullRequest",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_pull_request_merge_options",
        title: "Get pull request merge options",
        description:
          "Get merge eligibility, methods, and commit-email choices for a pull request.",
        inputSchema: repositoryPullRequest,
        service,
        method: "pullRequestMergeOptions",
        arguments: (value) => [value.owner, value.name, value.number, source],
        resultKey: "options",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_review_threads",
        title: "Get review threads",
        description: "List tracked GitHub review threads.",
        inputSchema: z.object({}),
        service,
        method: "reviewThreads",
        arguments: () => [],
        resultKey: "threads",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_actions_runs",
        title: "Get Actions runs",
        description:
          "List GitHub Actions workflow runs with repository and branch filters.",
        inputSchema: z.object({
          codebaseRepositoryId: z.string().nullable().optional(),
          branch: z.string().nullable().optional(),
          workflowId: z.string().nullable().optional(),
          first: z.number().int().min(1).max(100).default(25),
          after: z.string().nullable().optional(),
        }),
        service,
        method: "actionsWorkflowRuns",
        arguments: (value) => [
          value.codebaseRepositoryId,
          value.first,
          value.after,
          value.branch,
          value.workflowId,
          source,
        ],
        resultKey: "page",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_actions_jobs",
        title: "Get Actions jobs",
        description: "Get jobs for a GitHub Actions workflow run.",
        inputSchema: z.object({
          codebaseRepositoryId: z.string().min(1),
          workflowRunId: z.string().min(1),
        }),
        service,
        method: "actionsWorkflowJobs",
        arguments: (value) => [
          value.codebaseRepositoryId,
          value.workflowRunId,
          source,
        ],
        resultKey: "jobs",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_actions_run_attempt",
        title: "Get Actions run attempt",
        description: "Get one attempt of a GitHub Actions workflow run.",
        inputSchema: z.object({
          repositoryId: z.string().min(1),
          workflowRunId: z.string().min(1),
          attempt: z.number().int().positive(),
          includeJobs: z.boolean().default(true),
        }),
        service,
        method: "actionsWorkflowRunAttempt",
        arguments: (value) => [
          value.repositoryId,
          value.workflowRunId,
          value.attempt,
          value.includeJobs,
          source,
        ],
        resultKey: "attempt",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_repository_workflows",
        title: "Get repository workflows",
        description:
          "List GitHub Actions workflows for a configured repository.",
        inputSchema: z.object({ codebaseRepositoryId: z.string().min(1) }),
        service,
        method: "repositoryWorkflows",
        arguments: ({ codebaseRepositoryId }) => [codebaseRepositoryId, source],
        resultKey: "workflows",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_auto_retry_rules",
        title: "Get auto-retry rules",
        description: "List GitHub pipeline auto-retry rules.",
        inputSchema: z.object({
          codebaseRepositoryId: z.string().nullable().optional(),
          workflowRunId: z.string().nullable().optional(),
        }),
        service,
        method: "autoRetryRules",
        resultKey: "rules",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_github_rate_limits",
        title: "Get GitHub rate limits",
        description: "Get recently observed GitHub API rate-limit snapshots.",
        inputSchema: z.object({}),
        service,
        method: "rateLimitSnapshots",
        arguments: () => [],
        resultKey: "snapshots",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "create_pull_request",
        title: "Create pull request",
        description:
          "Create a GitHub pull request using configured GitHub App credentials.",
        inputSchema: z.object({
          owner: z.string().min(1),
          name: z.string().min(1),
          baseRefName: z.string().min(1),
          headRefName: z.string().min(1),
          title: z.string().min(1),
          body: z.string().nullable().optional(),
          draft: z.boolean().nullable().optional(),
        }),
        service,
        method: "createPullRequest",
        resultKey: "pullRequest",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "update_pull_request",
        title: "Update pull request",
        description:
          "Update a pull request title, body, or draft state on GitHub.",
        inputSchema: repositoryPullRequest.extend({
          title: z.string().nullable().optional(),
          body: z.string().nullable().optional(),
          draft: z.boolean().nullable().optional(),
        }),
        service,
        method: "updatePullRequest",
        resultKey: "pullRequest",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "submit_pull_request_review",
        title: "Submit pull request review",
        description:
          "Approve, comment on, or request changes to a pull request.",
        inputSchema: repositoryPullRequest.extend({
          event: z.enum(["APPROVE", "REQUEST_CHANGES", "COMMENT"]),
          body: z.string().nullable().optional(),
        }),
        service,
        method: "submitPullRequestReview",
        resultKey: "pullRequest",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "request_pull_request_reviewers",
        title: "Request pull request reviewers",
        description:
          "Request GitHub users or organization teams to review a pull request.",
        inputSchema: repositoryPullRequest.extend({
          reviewers: z.array(z.string()).default([]),
          teamReviewers: z.array(z.string()).default([]),
        }),
        service,
        method: "requestPullRequestReviewers",
        resultKey: "pullRequest",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "dispatch_github_workflow",
        title: "Dispatch GitHub workflow",
        description:
          "Dispatch a workflow_dispatch-enabled GitHub Actions workflow.",
        inputSchema: z.object({
          repositoryId: z.string().min(1),
          workflowId: z.string().min(1),
          ref: z.string().min(1),
          inputs: z.record(z.string(), z.string()).nullable().optional(),
        }),
        service,
        method: "dispatchWorkflow",
        resultKey: "dispatched",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "merge_pull_request",
        title: "Merge pull request",
        description:
          "Merge a GitHub pull request with an enabled merge method.",
        inputSchema: repositoryPullRequest.extend({
          method: z.enum(["MERGE", "SQUASH", "REBASE"]),
          commitHeadline: z.string().min(1),
          commitBody: z.string().default(""),
          authorEmail: z.string().nullable().optional(),
        }),
        service,
        method: "mergePullRequest",
        arguments: (value) => [value, source],
        resultKey: "pullRequest",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "set_pull_request_labels",
        title: "Set pull request labels",
        description: "Replace labels on a GitHub pull request.",
        inputSchema: repositoryPullRequest.extend({
          labels: z.array(z.string()),
        }),
        service,
        method: "setPullRequestLabels",
        resultKey: "pullRequest",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "reply_review_thread",
        title: "Reply to review thread",
        description: "Post a reply to a GitHub pull-request review thread.",
        inputSchema: z.object({
          threadId: z.string().min(1),
          body: z.string().min(1),
        }),
        service,
        method: "replyToReviewThread",
        arguments: ({ threadId, body }) => [threadId, body],
        resultKey: "thread",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "set_review_thread_resolved",
        title: "Set review thread resolved",
        description: "Resolve or unresolve a GitHub review thread.",
        inputSchema: z.object({
          threadId: z.string().min(1),
          resolved: z.boolean(),
        }),
        service,
        method: "setReviewThreadResolved",
        arguments: ({ threadId, resolved }) => [threadId, resolved],
        resultKey: "thread",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "retry_pipeline",
        title: "Retry pipeline",
        description: "Retry a failed GitHub check suite.",
        inputSchema: z.object({
          repositoryId: z.string().min(1),
          checkSuiteId: z.string().min(1),
        }),
        service,
        method: "retryPipeline",
        arguments: (value) => [
          value.repositoryId,
          value.checkSuiteId,
          source,
          audit,
        ],
        resultKey: "pipeline",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "retry_workflow_job",
        title: "Retry workflow job",
        description: "Retry one failed job in a GitHub Actions workflow run.",
        inputSchema: z.object({
          repositoryId: z.string().min(1),
          checkSuiteId: z.string().min(1),
          jobId: z.string().min(1),
        }),
        service,
        method: "retryWorkflowJob",
        arguments: (value) => [
          value.repositoryId,
          value.checkSuiteId,
          value.jobId,
          source,
          audit,
        ],
        resultKey: "job",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "cancel_actions_run",
        title: "Cancel Actions run",
        description: "Cancel a GitHub Actions workflow run.",
        inputSchema: z.object({
          codebaseRepositoryId: z.string().min(1),
          workflowRunId: z.string().min(1),
          force: z.boolean().default(false),
        }),
        service,
        method: "cancelActionsWorkflowRun",
        arguments: (value) => [
          value.codebaseRepositoryId,
          value.workflowRunId,
          value.force,
          source,
          audit,
        ],
        resultKey: "run",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "save_auto_retry_rule",
        title: "Save auto-retry rule",
        description: "Create or update a GitHub pipeline auto-retry rule.",
        inputSchema: z.object({
          id: z.string().nullable().optional(),
          scope: z.string().min(1),
          codebaseRepositoryId: z.string().min(1),
          repositoryGithubId: z.string().nullable().optional(),
          worktreeId: z.string().nullable().optional(),
          branch: z.string().nullable().optional(),
          pullRequestNumber: z.number().int().positive().nullable().optional(),
          allWorkflows: z.boolean(),
          mode: z.string().min(1),
          retryLimit: z.number().int().min(0).nullable().optional(),
          failureStrategy: z.string().min(1),
          targets: z.array(
            z.object({
              workflowId: z.string().nullable().optional(),
              workflowRunId: z.string().nullable().optional(),
              jobName: z.string().nullable().optional(),
            }),
          ),
        }),
        service,
        method: "saveAutoRetryRule",
        resultKey: "rule",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
    ],
  };
}
