import * as z from "zod/v4";

import type { JiraService } from "@/services/jira";

import {
  defineTool,
  READ_ONLY_EXTERNAL_ANNOTATIONS,
  WRITE_EXTERNAL_ANNOTATIONS,
  type BuiltInToolGroup,
} from "../builtin-tools";
import { redactSensitiveToolOutput, serviceTool } from "./service-tool";

const issueInput = z.object({ issueKey: z.string().min(1) });
const jiraText = z.object({ format: z.string().min(1), value: z.string() });

export function createJiraToolGroup(service: JiraService): BuiltInToolGroup {
  return {
    id: "builtin:jira",
    name: "Jira",
    children: [],
    tools: [
      serviceTool({
        name: "get_jira_status",
        title: "Get Jira status",
        description:
          "Test the configured Jira connection without exposing credentials.",
        inputSchema: z.object({}),
        service,
        method: "testConnection",
        arguments: () => [],
        resultKey: "status",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_jira_projects",
        title: "Get Jira projects",
        description: "List configured Jira projects and display settings.",
        inputSchema: z.object({}),
        service,
        method: "listProjects",
        arguments: () => [],
        resultKey: "projects",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      defineTool({
        name: "get_jira_sources",
        title: "Get Jira sources",
        description:
          "List ticket-board sources configured across Jira projects.",
        inputSchema: z.object({}),
        outputSchema: z.object({ sources: z.unknown() }),
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
        handler: async () => ({
          sources: redactSensitiveToolOutput(
            (await service.listProjects()).flatMap(
              (project) => project.sources,
            ),
          ),
        }),
      }),
      serviceTool({
        name: "get_jira_board",
        title: "Get Jira board",
        description: "Get tickets for a configured Jira source.",
        inputSchema: z.object({
          sourceId: z.string().min(1),
          refresh: z.boolean().default(false),
        }),
        service,
        method: "ticketBoard",
        arguments: ({ sourceId, refresh }) => [sourceId, refresh],
        resultKey: "board",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_jira_ticket",
        title: "Get Jira ticket",
        description: "Get a Jira ticket and its normalized editable metadata.",
        inputSchema: issueInput.extend({ refresh: z.boolean().default(false) }),
        service,
        method: "ticket",
        arguments: ({ issueKey, refresh }) => [issueKey, refresh],
        resultKey: "ticket",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_jira_assignable_users",
        title: "Get Jira assignable users",
        description: "Search users who can be assigned to a Jira ticket.",
        inputSchema: issueInput.extend({ query: z.string().default("") }),
        service,
        method: "assignableUsers",
        arguments: ({ issueKey, query }) => [issueKey, query],
        resultKey: "users",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_jira_transitions",
        title: "Get Jira transitions",
        description: "Get available transitions for a Jira ticket.",
        inputSchema: issueInput,
        service,
        method: "ticketTransitions",
        arguments: ({ issueKey }) => [issueKey],
        resultKey: "transitions",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_jira_edit_fields",
        title: "Get Jira edit fields",
        description:
          "Get editable fields and allowed values for a Jira ticket.",
        inputSchema: issueInput,
        service,
        method: "ticketEditFields",
        arguments: ({ issueKey }) => [issueKey],
        resultKey: "fields",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_jira_ticket_changes",
        title: "Get Jira ticket changes",
        description: "Get paginated Jira ticket changelog entries.",
        inputSchema: issueInput.extend({
          limit: z.number().int().min(1).max(200).default(50),
          offset: z.number().int().min(0).default(0),
        }),
        service,
        method: "ticketChanges",
        arguments: (value) => [value.issueKey, value.limit, value.offset],
        resultKey: "page",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "get_jira_worklogs",
        title: "Get Jira worklogs",
        description: "Get paginated worklogs for a Jira ticket.",
        inputSchema: issueInput.extend({
          limit: z.number().int().min(1).max(200).default(50),
          offset: z.number().int().min(0).default(0),
        }),
        service,
        method: "ticketWorklogs",
        arguments: (value) => [value.issueKey, value.limit, value.offset],
        resultKey: "page",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "add_jira_comment",
        title: "Add Jira comment",
        description: "Add a plain-text or Markdown comment to a Jira ticket.",
        inputSchema: issueInput.extend({ content: jiraText }),
        service,
        method: "addComment",
        arguments: ({ issueKey, content }) => [issueKey, content],
        resultKey: "ticket",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "assign_jira_ticket",
        title: "Assign Jira ticket",
        description: "Assign or unassign a Jira ticket.",
        inputSchema: issueInput.extend({
          accountId: z.string().nullable().optional(),
        }),
        service,
        method: "assignTicket",
        arguments: ({ issueKey, accountId }) => [issueKey, accountId ?? null],
        resultKey: "ticket",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "transition_jira_ticket",
        title: "Transition Jira ticket",
        description: "Apply an available status transition to a Jira ticket.",
        inputSchema: issueInput.extend({ transitionId: z.string().min(1) }),
        service,
        method: "transitionTicket",
        arguments: ({ issueKey, transitionId }) => [issueKey, transitionId],
        resultKey: "ticket",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "update_jira_ticket",
        title: "Update Jira ticket",
        description: "Update supported editable fields on a Jira ticket.",
        inputSchema: issueInput.extend({
          summary: z.string().nullable().optional(),
          description: jiraText.nullable().optional(),
          priorityId: z.string().nullable().optional(),
          labels: z.array(z.string()).nullable().optional(),
          componentIds: z.array(z.string()).nullable().optional(),
          fixVersionIds: z.array(z.string()).nullable().optional(),
          affectedVersionIds: z.array(z.string()).nullable().optional(),
          dueDate: z.string().nullable().optional(),
        }),
        service,
        method: "updateTicket",
        resultKey: "ticket",
        annotations: WRITE_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "resolve_jira_branch",
        title: "Resolve Jira branch",
        description: "Resolve the configured branch name for a Jira ticket.",
        inputSchema: issueInput,
        service,
        method: "branchTicket",
        arguments: ({ issueKey }) => [issueKey],
        resultKey: "branch",
        annotations: READ_ONLY_EXTERNAL_ANNOTATIONS,
      }),
      serviceTool({
        name: "create_jira_ticket",
        title: "Create Jira ticket",
        description:
          "Create a Jira ticket with typed core fields and optional additional fields.",
        inputSchema: z.object({
          projectKey: z.string().min(1),
          issueTypeId: z.string().min(1),
          summary: z.string().min(1),
          description: jiraText.nullable().optional(),
          fields: z.record(z.string(), z.unknown()).nullable().optional(),
        }),
        service,
        method: "createTicket",
        resultKey: "ticket",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "add_jira_worklog",
        title: "Add Jira worklog",
        description: "Add a time-spent worklog to a Jira ticket.",
        inputSchema: issueInput.extend({
          timeSpentSeconds: z.number().int().positive(),
          startedAt: z.string().nullable().optional(),
          comment: jiraText.nullable().optional(),
        }),
        service,
        method: "addWorklog",
        resultKey: "ticket",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "link_jira_tickets",
        title: "Link Jira tickets",
        description: "Create a typed relationship between two Jira tickets.",
        inputSchema: z.object({
          inwardIssueKey: z.string().min(1),
          outwardIssueKey: z.string().min(1),
          linkType: z.string().min(1),
        }),
        service,
        method: "linkTickets",
        resultKey: "ticket",
        annotations: { ...WRITE_EXTERNAL_ANNOTATIONS, idempotentHint: false },
      }),
    ],
  };
}
