import * as z from "zod/v4";

import type { RunsService } from "@/services/runs";

import {
  DESTRUCTIVE_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  type BuiltInToolGroup,
} from "../builtin-tools";
import { serviceTool } from "./service-tool";

const runId = z.object({ runId: z.string().min(1) });
const runConfiguration = z.object({
  kind: z.string().min(1),
  worktreeId: z.string().min(1),
  jiraIssueKey: z.string().nullable().optional(),
  provider: z.string().min(1),
  model: z.string().min(1),
  effort: z.string().nullable().optional(),
  webSearchEnabled: z.boolean().nullable().optional(),
  prompt: z.string().min(1),
  attachmentIds: z.array(z.string().min(1)).nullable().optional(),
  draftId: z.string().nullable().optional(),
  sourcePlanId: z.string().nullable().optional(),
  parentRunId: z.string().nullable().optional(),
  followUpMode: z.string().nullable().optional(),
  contextMode: z.string().nullable().optional(),
});

export function createRunToolGroup(service: RunsService): BuiltInToolGroup {
  return {
    id: "builtin:agent-runs",
    name: "Agent Runs",
    children: [],
    tools: [
      serviceTool({
        name: "get_agent_runs",
        title: "Get agent runs",
        description:
          "List agent runs with kind, archive, provider, origin, search, and pagination filters.",
        inputSchema: z.object({
          kind: z.enum(["SESSION", "PLAN"]).default("SESSION"),
          search: z.string().nullable().optional(),
          archive: z.string().default("ACTIVE"),
          provider: z.string().nullable().optional(),
          origin: z.string().nullable().optional(),
          first: z.number().int().min(1).max(200).default(100),
          after: z.string().nullable().optional(),
        }),
        service,
        method: "list",
        resultKey: "page",
      }),
      serviceTool({
        name: "get_agent_run",
        title: "Get agent run",
        description:
          "Get an agent run without exposing its native session transcript.",
        inputSchema: runId,
        service,
        method: "get",
        arguments: ({ runId: id }) => [id],
        resultKey: "run",
      }),
      serviceTool({
        name: "get_run_events",
        title: "Get run events",
        description:
          "Get normalized run events; native provider payloads are redacted.",
        inputSchema: runId.extend({
          search: z.string().nullable().optional(),
          afterSequence: z.number().int().default(-1),
          first: z.number().int().min(1).max(500).default(200),
          includeSuperseded: z.boolean().default(false),
        }),
        service,
        method: "events",
        resultKey: "events",
      }),
      serviceTool({
        name: "get_run_questions",
        title: "Get run questions",
        description: "Get question batches for a run.",
        inputSchema: runId.extend({
          first: z.number().int().min(1).max(200).default(100),
          after: z.string().nullable().optional(),
        }),
        service,
        method: "questions",
        resultKey: "page",
      }),
      serviceTool({
        name: "get_run_usage",
        title: "Get run usage",
        description: "Get token and cost usage summarized for a run.",
        inputSchema: runId,
        service,
        method: "usage",
        arguments: ({ runId: id }) => [id],
        resultKey: "usage",
      }),
      serviceTool({
        name: "get_run_linked_items",
        title: "Get linked run items",
        description:
          "Get runs linked by follow-up, plan, or parent relationships.",
        inputSchema: runId,
        service,
        method: "linkedItems",
        arguments: ({ runId: id }) => [id],
        resultKey: "runs",
      }),
      serviceTool({
        name: "get_run_provider_catalog",
        title: "Get run provider catalog",
        description:
          "Get provider, model, and reasoning-effort choices for a run or worktree.",
        inputSchema: z.object({
          runId: z.string().nullable().optional(),
          worktreeId: z.string().nullable().optional(),
        }),
        service,
        method: "providerCatalog",
        resultKey: "providers",
      }),
      serviceTool({
        name: "create_agent_run",
        title: "Create agent run",
        description: "Create and queue a new agent run.",
        inputSchema: runConfiguration,
        service,
        method: "create",
        resultKey: "run",
        annotations: { ...WRITE_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "play_plan",
        title: "Play plan",
        description: "Create a run from an existing plan run.",
        inputSchema: z.object({ planId: z.string().min(1) }),
        service,
        method: "playPlan",
        arguments: ({ planId }) => [planId],
        resultKey: "run",
        annotations: { ...WRITE_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "create_run_follow_up",
        title: "Create run follow-up",
        description: "Create a follow-up run linked to a source run.",
        inputSchema: z.object({
          sourceId: z.string().min(1),
          input: runConfiguration,
        }),
        service,
        method: "followUp",
        arguments: ({ sourceId, input }) => [sourceId, input],
        resultKey: "run",
        annotations: { ...WRITE_ANNOTATIONS, idempotentHint: false },
      }),
      serviceTool({
        name: "steer_agent_run",
        title: "Steer agent run",
        description: "Send additional guidance to an active run.",
        inputSchema: runId.extend({
          prompt: z.string().min(1),
          attachmentIds: z.array(z.string().min(1)).default([]),
        }),
        service,
        method: "steer",
        arguments: (value) => [value.runId, value.prompt, value.attachmentIds],
        resultKey: "run",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "answer_run_question",
        title: "Answer run question",
        description: "Answer a pending agent question batch.",
        inputSchema: z.object({
          batchId: z.string().min(1),
          answers: z.unknown(),
        }),
        service,
        method: "answerQuestion",
        arguments: ({ batchId, answers }) => [batchId, answers],
        resultKey: "run",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "revise_run_answer",
        title: "Revise run answer",
        description:
          "Revise an answer and optionally stash or roll back worktree changes.",
        inputSchema: z.object({
          batchId: z.string().min(1),
          answers: z.unknown(),
          stash: z.boolean().default(false),
          rollback: z.boolean().default(true),
        }),
        service,
        method: "reviseAnswer",
        arguments: (value) => [
          value.batchId,
          value.answers,
          value.stash,
          value.rollback,
        ],
        resultKey: "run",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "pause_agent_run",
        title: "Pause agent run",
        description: "Pause an active agent run.",
        inputSchema: runId,
        service,
        method: "lifecycle",
        arguments: ({ runId: id }) => [id, "PAUSE"],
        resultKey: "run",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "continue_agent_run",
        title: "Continue agent run",
        description: "Continue a paused agent run.",
        inputSchema: runId,
        service,
        method: "lifecycle",
        arguments: ({ runId: id }) => [id, "CONTINUE"],
        resultKey: "run",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "cancel_agent_run",
        title: "Cancel agent run",
        description: "Cancel an active agent run.",
        inputSchema: runId,
        service,
        method: "lifecycle",
        arguments: ({ runId: id }) => [id, "CANCEL"],
        resultKey: "run",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "archive_agent_runs",
        title: "Archive agent runs",
        description: "Archive or restore agent runs.",
        inputSchema: z.object({
          ids: z.array(z.string().min(1)).min(1),
          archived: z.boolean().default(true),
        }),
        service,
        method: "archive",
        arguments: ({ ids, archived }) => [ids, archived],
        resultKey: "count",
        annotations: WRITE_ANNOTATIONS,
      }),
      serviceTool({
        name: "delete_agent_runs",
        title: "Delete agent runs",
        description:
          "Permanently delete agent runs and their stored normalized history.",
        inputSchema: z.object({ ids: z.array(z.string().min(1)).min(1) }),
        service,
        method: "deleteRuns",
        arguments: ({ ids }) => [ids],
        resultKey: "count",
        annotations: DESTRUCTIVE_ANNOTATIONS,
      }),
    ],
  };
}
