import {
  Bell,
  BellRing,
  Boxes,
  ChartNoAxesCombined,
  CircleDollarSign,
  ClipboardList,
  Combine,
  Cpu,
  Database,
  DatabaseZap,
  FilePenLine,
  FolderGit2,
  GitBranch,
  GitCompare,
  GitFork,
  GitPullRequest,
  Hammer,
  HardDrive,
  KeyRound,
  ListTodo,
  MessageSquareText,
  MessagesSquare,
  MousePointerClick,
  PlayCircle,
  Plus,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Terminal,
  TicketCheck,
  TimerReset,
  UserPlus,
  UsersRound,
  Waypoints,
  Webhook,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export type NavigationFeature =
  | "actionsCache"
  | "webhooks"
  | "jiraWebhooks"
  | "github"
  | "gitlab"
  | "gitlabWebhooks";
export type NavigationSection =
  "dashboard" | "ai" | "debugging" | "github" | "gitlab" | "jira" | "system";

export type AppDestination = {
  key: string;
  href: string;
  labelKey: string;
  aliases: string[];
  icon: LucideIcon;
  section: NavigationSection;
  sidebar: boolean;
  common?: boolean;
  feature?: NavigationFeature;
  features?: NavigationFeature[];
  activePrefixes?: string[];
  exact?: boolean;
};

export type NavigationFeatures = Record<
  "actionsCache" | "webhooks" | "jiraWebhooks",
  boolean
> &
  Partial<Record<"github" | "gitlab" | "gitlabWebhooks", boolean>>;

export const NAVIGATION_SECTIONS: NavigationSection[] = [
  "dashboard",
  "ai",
  "debugging",
  "github",
  "gitlab",
  "jira",
  "system",
];

export const APP_DESTINATIONS: AppDestination[] = [
  {
    key: "action-center",
    href: "/",
    labelKey: "actionCenter",
    aliases: ["attention", "tasks", "home"],
    icon: ListTodo,
    section: "dashboard",
    sidebar: true,
    common: true,
    exact: true,
  },
  {
    key: "apps",
    href: "/apps",
    labelKey: "apps",
    aliases: ["products", "projects", "application management"],
    icon: Boxes,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "notifications",
    href: "/notifications",
    labelKey: "notifications",
    aliases: ["alerts"],
    icon: Bell,
    section: "dashboard",
    sidebar: true,
  },
  {
    key: "agents",
    href: "/agents",
    labelKey: "agents",
    aliases: ["workers", "jobs"],
    icon: Cpu,
    section: "dashboard",
    sidebar: true,
    common: true,
    activePrefixes: ["/agents", "/jobs"],
  },
  {
    key: "workflows",
    href: "/workflows",
    labelKey: "workflows",
    aliases: ["automations", "workflow runs"],
    icon: Waypoints,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "commands",
    href: "/commands",
    labelKey: "commands",
    aliases: ["scripts", "command runs"],
    icon: Terminal,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "codebases",
    href: "/codebases",
    labelKey: "codebases",
    aliases: ["repositories", "repos"],
    icon: FolderGit2,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "worktrees",
    href: "/worktrees",
    labelKey: "worktrees",
    aliases: ["branches", "checkouts"],
    icon: GitBranch,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "changes",
    href: "/changes",
    labelKey: "changes",
    aliases: ["diffs", "patches", "review", "coverage"],
    icon: GitCompare,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "builds",
    href: "/builds",
    labelKey: "builds",
    aliases: ["recent builds", "xcode"],
    icon: Hammer,
    section: "dashboard",
    sidebar: true,
    common: true,
  },

  {
    key: "plans",
    href: "/plans",
    labelKey: "plans",
    aliases: ["ai plans"],
    icon: ClipboardList,
    section: "ai",
    sidebar: true,
  },
  {
    key: "sessions",
    href: "/sessions",
    labelKey: "sessions",
    aliases: ["ai sessions", "chats"],
    icon: MessagesSquare,
    section: "ai",
    sidebar: true,
  },
  {
    key: "drafts",
    href: "/drafts",
    labelKey: "drafts",
    aliases: ["new run"],
    icon: FilePenLine,
    section: "ai",
    sidebar: true,
    activePrefixes: ["/drafts", "/runs/new"],
  },
  {
    key: "usage",
    href: "/usage",
    labelKey: "usage",
    aliases: ["tokens"],
    icon: ChartNoAxesCombined,
    section: "ai",
    sidebar: true,
  },
  {
    key: "costs",
    href: "/costs",
    labelKey: "costs",
    aliases: ["spend", "pricing"],
    icon: CircleDollarSign,
    section: "ai",
    sidebar: true,
  },
  {
    key: "skills",
    href: "/skills",
    labelKey: "skills",
    aliases: ["capabilities"],
    icon: Sparkles,
    section: "ai",
    sidebar: true,
  },

  {
    key: "push-notifications",
    href: "/push-notifications",
    labelKey: "pushNotifications",
    aliases: ["apns"],
    icon: BellRing,
    section: "debugging",
    sidebar: true,
  },
  {
    key: "console-logs",
    href: "/console-logs",
    labelKey: "consoleLogs",
    aliases: ["logs"],
    icon: Terminal,
    section: "debugging",
    sidebar: true,
  },
  {
    key: "analytics-events",
    href: "/analytics-events",
    labelKey: "analyticsEvents",
    aliases: ["analytics"],
    icon: MousePointerClick,
    section: "debugging",
    sidebar: true,
  },
  {
    key: "unified-events",
    href: "/unified-events",
    labelKey: "unifiedEvents",
    aliases: ["events"],
    icon: Combine,
    section: "debugging",
    sidebar: true,
  },

  {
    key: "pull-requests",
    href: "/pull-requests",
    labelKey: "pullRequests",
    aliases: ["prs", "github prs"],
    icon: GitPullRequest,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "actions",
    href: "/actions",
    labelKey: "actions",
    aliases: ["github actions", "ci", "pipelines"],
    icon: PlayCircle,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "webhooks",
    href: "/webhooks",
    labelKey: "webhooks",
    aliases: ["github webhooks"],
    icon: Webhook,
    section: "github",
    sidebar: true,
    feature: "webhooks",
  },
  {
    key: "comments",
    href: "/comments",
    labelKey: "comments",
    aliases: ["reviews", "review threads"],
    icon: MessageSquareText,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "github-cache",
    href: "/github-cache",
    labelKey: "cache",
    aliases: ["github cache"],
    icon: Database,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "actions-cache",
    href: "/actions-cache",
    labelKey: "actionsCache",
    aliases: ["github actions cache"],
    icon: DatabaseZap,
    section: "github",
    sidebar: true,
    features: ["github", "actionsCache"],
  },

  {
    key: "gitlab-merge-requests",
    href: "/gitlab/merge-requests",
    labelKey: "mergeRequests",
    aliases: ["gitlab merge requests", "mrs"],
    icon: GitFork,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },
  {
    key: "gitlab-pipelines",
    href: "/gitlab/pipelines",
    labelKey: "pipelines",
    aliases: ["gitlab ci", "gitlab pipelines"],
    icon: PlayCircle,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },
  {
    key: "gitlab-webhooks",
    href: "/gitlab/webhooks",
    labelKey: "webhooks",
    aliases: ["gitlab webhooks"],
    icon: Webhook,
    section: "gitlab",
    sidebar: true,
    features: ["gitlab", "gitlabWebhooks"],
  },
  {
    key: "gitlab-comments",
    href: "/gitlab/comments",
    labelKey: "comments",
    aliases: ["gitlab discussions", "gitlab comments"],
    icon: MessageSquareText,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },
  {
    key: "gitlab-cache",
    href: "/gitlab/cache",
    labelKey: "apiCache",
    aliases: ["gitlab api cache"],
    icon: Database,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },

  {
    key: "jira-tickets",
    href: "/jira/tickets",
    labelKey: "tickets",
    aliases: ["jira tickets", "issues"],
    icon: TicketCheck,
    section: "jira",
    sidebar: true,
    common: true,
  },
  {
    key: "jira-webhooks",
    href: "/jira-webhooks",
    labelKey: "webhooks",
    aliases: ["jira webhooks"],
    icon: Webhook,
    section: "jira",
    sidebar: true,
    feature: "jiraWebhooks",
  },
  {
    key: "jira-cache",
    href: "/jira-cache",
    labelKey: "cache",
    aliases: ["jira cache"],
    icon: Database,
    section: "jira",
    sidebar: true,
  },

  {
    key: "polling",
    href: "/polling",
    labelKey: "polling",
    aliases: ["pollers"],
    icon: TimerReset,
    section: "system",
    sidebar: true,
  },
  {
    key: "build-data",
    href: "/build-data",
    labelKey: "buildData",
    aliases: ["derived data", "storage"],
    icon: HardDrive,
    section: "system",
    sidebar: true,
  },
  {
    key: "provisioning-profiles",
    href: "/provisioning-profiles",
    labelKey: "provisioningProfiles",
    aliases: ["profiles", "signing"],
    icon: ShieldCheck,
    section: "system",
    sidebar: true,
  },
  {
    key: "devices",
    href: "/devices",
    labelKey: "devices",
    aliases: ["ios devices"],
    icon: Smartphone,
    section: "system",
    sidebar: true,
  },
  {
    key: "users",
    href: "/users",
    labelKey: "users",
    aliases: ["accounts", "authentication"],
    icon: UsersRound,
    section: "system",
    sidebar: true,
  },
  {
    key: "api-keys",
    href: "/api-keys",
    labelKey: "apiKeys",
    aliases: ["tokens", "mcp authentication"],
    icon: KeyRound,
    section: "system",
    sidebar: true,
  },
  {
    key: "tools",
    href: "/tools",
    labelKey: "tools",
    aliases: ["mcp tools"],
    icon: Wrench,
    section: "system",
    sidebar: true,
  },
  {
    key: "credentials",
    href: "/credentials",
    labelKey: "credentials",
    aliases: ["secrets", "tokens"],
    icon: KeyRound,
    section: "system",
    sidebar: true,
  },
  {
    key: "settings",
    href: "/settings",
    labelKey: "settings",
    aliases: ["configuration"],
    icon: Settings,
    section: "system",
    sidebar: true,
  },

  {
    key: "new-workflow",
    href: "/workflows/new",
    labelKey: "newWorkflow",
    aliases: ["create workflow", "automation"],
    icon: Plus,
    section: "dashboard",
    sidebar: false,
  },
  {
    key: "new-command",
    href: "/commands/new",
    labelKey: "newCommand",
    aliases: ["create command", "script"],
    icon: Plus,
    section: "dashboard",
    sidebar: false,
  },
  {
    key: "new-run",
    href: "/runs/new",
    labelKey: "newRun",
    aliases: ["start run", "draft"],
    icon: PlayCircle,
    section: "ai",
    sidebar: false,
  },
  {
    key: "enroll-device",
    href: "/devices/enroll",
    labelKey: "enrollDevice",
    aliases: ["add device", "register device"],
    icon: UserPlus,
    section: "system",
    sidebar: false,
  },
  {
    key: "skill-groups",
    href: "/skills/groups",
    labelKey: "skillGroups",
    aliases: ["groups"],
    icon: Sparkles,
    section: "ai",
    sidebar: false,
  },
];

export function destinationVisible(
  destination: AppDestination,
  features: NavigationFeatures,
): boolean {
  const required = [
    ...(destination.feature ? [destination.feature] : []),
    ...(destination.features ?? []),
  ];
  return required.every((feature) => features[feature]);
}

export function destinationActive(
  destination: AppDestination,
  pathname: string,
): boolean {
  if (destination.exact) return pathname === destination.href;
  const prefixes = destination.activePrefixes ?? [destination.href];
  return prefixes.some(
    (prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
  );
}
