import {
  Activity,
  Bell,
  BellRing,
  Boxes,
  Bug,
  ChartNoAxesCombined,
  CircleDollarSign,
  ClipboardList,
  Combine,
  Cpu,
  Database,
  DatabaseZap,
  FilePenLine,
  FolderGit2,
  GitBranch,
  GitCompare,
  GitFork,
  GitPullRequest,
  Hammer,
  HardDrive,
  KeyRound,
  ListTodo,
  MessageSquareText,
  MessagesSquare,
  MousePointerClick,
  Network,
  PlayCircle,
  Plus,
  RadioTower,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Terminal,
  TicketCheck,
  TimerReset,
  UserPlus,
  UsersRound,
  Waypoints,
  Webhook,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export type NavigationFeature =
  | "actionsCache"
  | "webhooks"
  | "jiraWebhooks"
  | "github"
  | "gitlab"
  | "gitlabWebhooks";
export type NavigationSection =
  "dashboard" | "ai" | "debugging" | "github" | "gitlab" | "jira" | "system";

export type AppDestination = {
  key: string;
  href: string;
  labelKey: string;
  aliases: string[];
  icon: LucideIcon;
  section: NavigationSection;
  sidebar: boolean;
  common?: boolean;
  feature?: NavigationFeature;
  features?: NavigationFeature[];
  activePrefixes?: string[];
  exact?: boolean;
};

export type NavigationFeatures = Record<
  "actionsCache" | "webhooks" | "jiraWebhooks",
  boolean
> &
  Partial<Record<"github" | "gitlab" | "gitlabWebhooks", boolean>>;

export const NAVIGATION_SECTIONS: NavigationSection[] = [
  "dashboard",
  "ai",
  "debugging",
  "github",
  "gitlab",
  "jira",
  "system",
];

export const APP_DESTINATIONS: AppDestination[] = [
  {
    key: "action-center",
    href: "/dashboard/action-center",
    labelKey: "actionCenter",
    aliases: ["attention", "tasks", "home"],
    icon: ListTodo,
    section: "dashboard",
    sidebar: true,
    common: true,
    exact: true,
  },
  {
    key: "apps",
    href: "/dashboard/apps",
    labelKey: "apps",
    aliases: ["products", "projects", "application management"],
    icon: Boxes,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "notifications",
    href: "/dashboard/notifications",
    labelKey: "notifications",
    aliases: ["alerts"],
    icon: Bell,
    section: "dashboard",
    sidebar: true,
  },
  {
    key: "agents",
    href: "/dashboard/agents",
    labelKey: "agents",
    aliases: ["workers", "jobs"],
    icon: Cpu,
    section: "dashboard",
    sidebar: true,
    common: true,
    activePrefixes: ["/dashboard/agents", "/dashboard/jobs"],
  },
  {
    key: "workflows",
    href: "/dashboard/workflows",
    labelKey: "workflows",
    aliases: ["automations", "workflow runs"],
    icon: Waypoints,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "commands",
    href: "/dashboard/commands",
    labelKey: "commands",
    aliases: ["scripts", "command runs"],
    icon: Terminal,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "codebases",
    href: "/dashboard/codebases",
    labelKey: "codebases",
    aliases: ["repositories", "repos"],
    icon: FolderGit2,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "worktrees",
    href: "/dashboard/worktrees",
    labelKey: "worktrees",
    aliases: ["branches", "checkouts"],
    icon: GitBranch,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "changes",
    href: "/dashboard/changes",
    labelKey: "changes",
    aliases: ["diffs", "patches", "review", "coverage"],
    icon: GitCompare,
    section: "dashboard",
    sidebar: true,
    common: true,
  },
  {
    key: "builds",
    href: "/dashboard/builds",
    labelKey: "builds",
    aliases: ["recent builds", "xcode"],
    icon: Hammer,
    section: "dashboard",
    sidebar: true,
    common: true,
  },

  {
    key: "plans",
    href: "/ai/plans",
    labelKey: "plans",
    aliases: ["ai plans"],
    icon: ClipboardList,
    section: "ai",
    sidebar: true,
  },
  {
    key: "sessions",
    href: "/ai/sessions",
    labelKey: "sessions",
    aliases: ["ai sessions", "chats"],
    icon: MessagesSquare,
    section: "ai",
    sidebar: true,
  },
  {
    key: "drafts",
    href: "/ai/drafts",
    labelKey: "drafts",
    aliases: ["new run"],
    icon: FilePenLine,
    section: "ai",
    sidebar: true,
    activePrefixes: ["/ai/drafts", "/ai/drafts/new"],
  },
  {
    key: "usage",
    href: "/ai/usage",
    labelKey: "usage",
    aliases: ["tokens"],
    icon: ChartNoAxesCombined,
    section: "ai",
    sidebar: true,
  },
  {
    key: "costs",
    href: "/ai/costs",
    labelKey: "costs",
    aliases: ["spend", "pricing"],
    icon: CircleDollarSign,
    section: "ai",
    sidebar: true,
  },
  {
    key: "skills",
    href: "/ai/skills",
    labelKey: "skills",
    aliases: ["capabilities"],
    icon: Sparkles,
    section: "ai",
    sidebar: true,
  },

  {
    key: "sse",
    href: "/debugging/sse",
    labelKey: "sseEndpoints",
    aliases: [
      "server sent events",
      "event streams",
      "sse history",
      "sse mocks",
    ],
    icon: RadioTower,
    section: "debugging",
    sidebar: true,
    activePrefixes: ["/debugging/sse"],
  },
  {
    key: "push-notifications",
    href: "/debugging/push-notifications",
    labelKey: "pushNotifications",
    aliases: ["apns"],
    icon: BellRing,
    section: "debugging",
    sidebar: true,
  },
  {
    key: "console-logs",
    href: "/debugging/console-logs",
    labelKey: "consoleLogs",
    aliases: ["logs"],
    icon: Terminal,
    section: "debugging",
    sidebar: true,
  },
  {
    key: "analytics-events",
    href: "/debugging/analytics-events",
    labelKey: "analyticsEvents",
    aliases: ["analytics"],
    icon: MousePointerClick,
    section: "debugging",
    sidebar: true,
  },
  {
    key: "unified-events",
    href: "/debugging/unified-events",
    labelKey: "unifiedEvents",
    aliases: ["events"],
    icon: Combine,
    section: "debugging",
    sidebar: true,
  },
  {
    key: "crashes",
    href: "/debugging/crashes",
    labelKey: "crashes",
    aliases: ["crash reports", "dsym", "dsyms", "symbolication", "symbolicate"],
    icon: Bug,
    section: "debugging",
    sidebar: true,
    activePrefixes: ["/debugging/crashes"],
  },

  {
    key: "pull-requests",
    href: "/github/pull-requests",
    labelKey: "pullRequests",
    aliases: ["prs", "github prs"],
    icon: GitPullRequest,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "actions",
    href: "/github/actions",
    labelKey: "actions",
    aliases: ["github actions", "ci", "pipelines"],
    icon: PlayCircle,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "webhooks",
    href: "/github/webhooks",
    labelKey: "webhooks",
    aliases: ["github webhooks"],
    icon: Webhook,
    section: "github",
    sidebar: true,
    feature: "webhooks",
  },
  {
    key: "comments",
    href: "/github/comments",
    labelKey: "comments",
    aliases: ["reviews", "review threads"],
    icon: MessageSquareText,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "github-cache",
    href: "/github/cache",
    labelKey: "cache",
    aliases: ["github cache"],
    icon: Database,
    section: "github",
    sidebar: true,
    feature: "github",
  },
  {
    key: "actions-cache",
    href: "/github/actions-cache",
    labelKey: "actionsCache",
    aliases: ["github actions cache"],
    icon: DatabaseZap,
    section: "github",
    sidebar: true,
    features: ["github", "actionsCache"],
  },

  {
    key: "gitlab-merge-requests",
    href: "/gitlab/merge-requests",
    labelKey: "mergeRequests",
    aliases: ["gitlab merge requests", "mrs"],
    icon: GitFork,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },
  {
    key: "gitlab-pipelines",
    href: "/gitlab/pipelines",
    labelKey: "pipelines",
    aliases: ["gitlab ci", "gitlab pipelines"],
    icon: PlayCircle,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },
  {
    key: "gitlab-webhooks",
    href: "/gitlab/webhooks",
    labelKey: "webhooks",
    aliases: ["gitlab webhooks"],
    icon: Webhook,
    section: "gitlab",
    sidebar: true,
    features: ["gitlab", "gitlabWebhooks"],
  },
  {
    key: "gitlab-comments",
    href: "/gitlab/comments",
    labelKey: "comments",
    aliases: ["gitlab discussions", "gitlab comments"],
    icon: MessageSquareText,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },
  {
    key: "gitlab-cache",
    href: "/gitlab/cache",
    labelKey: "cache",
    aliases: ["gitlab cache", "gitlab api cache"],
    icon: Database,
    section: "gitlab",
    sidebar: true,
    feature: "gitlab",
  },

  {
    key: "jira-tickets",
    href: "/jira/tickets",
    labelKey: "tickets",
    aliases: ["jira tickets", "issues"],
    icon: TicketCheck,
    section: "jira",
    sidebar: true,
    common: true,
  },
  {
    key: "jira-webhooks",
    href: "/jira/webhooks",
    labelKey: "webhooks",
    aliases: ["jira webhooks"],
    icon: Webhook,
    section: "jira",
    sidebar: true,
    feature: "jiraWebhooks",
  },
  {
    key: "jira-cache",
    href: "/jira/cache",
    labelKey: "cache",
    aliases: ["jira cache"],
    icon: Database,
    section: "jira",
    sidebar: true,
  },

  {
    key: "status",
    href: "/system/status",
    labelKey: "status",
    aliases: ["health", "versions", "cli health"],
    icon: Activity,
    section: "system",
    sidebar: true,
  },
  {
    key: "prepare",
    href: "/system/prepare",
    labelKey: "prepare",
    aliases: ["preparations", "worktree preparations"],
    icon: Sparkles,
    section: "system",
    sidebar: true,
  },
  {
    key: "polling",
    href: "/system/polling",
    labelKey: "polling",
    aliases: ["pollers"],
    icon: TimerReset,
    section: "system",
    sidebar: true,
  },
  {
    key: "build-data",
    href: "/system/build-data",
    labelKey: "buildData",
    aliases: ["derived data", "storage"],
    icon: HardDrive,
    section: "system",
    sidebar: true,
  },
  {
    key: "tailscale",
    href: "/system/tailscale",
    labelKey: "tailscale",
    aliases: ["tailscale serve", "funnel", "port forwarding", "tailnet"],
    icon: Network,
    section: "system",
    sidebar: true,
  },
  {
    key: "provisioning-profiles",
    href: "/system/provisioning-profiles",
    labelKey: "provisioningProfiles",
    aliases: ["profiles", "signing"],
    icon: ShieldCheck,
    section: "system",
    sidebar: true,
  },
  {
    key: "devices",
    href: "/system/devices",
    labelKey: "devices",
    aliases: ["ios devices"],
    icon: Smartphone,
    section: "system",
    sidebar: true,
  },
  {
    key: "users",
    href: "/system/users",
    labelKey: "users",
    aliases: ["accounts", "authentication"],
    icon: UsersRound,
    section: "system",
    sidebar: true,
  },
  {
    key: "api-keys",
    href: "/system/api-keys",
    labelKey: "apiKeys",
    aliases: ["tokens", "mcp authentication"],
    icon: KeyRound,
    section: "system",
    sidebar: true,
  },
  {
    key: "tools",
    href: "/system/tools",
    labelKey: "tools",
    aliases: ["mcp tools"],
    icon: Wrench,
    section: "system",
    sidebar: true,
  },
  {
    key: "credentials",
    href: "/system/credentials",
    labelKey: "credentials",
    aliases: ["secrets", "tokens"],
    icon: KeyRound,
    section: "system",
    sidebar: true,
  },
  {
    key: "settings",
    href: "/system/settings",
    labelKey: "settings",
    aliases: ["configuration"],
    icon: Settings,
    section: "system",
    sidebar: true,
  },

  {
    key: "new-workflow",
    href: "/dashboard/workflows/new",
    labelKey: "newWorkflow",
    aliases: ["create workflow", "automation"],
    icon: Plus,
    section: "dashboard",
    sidebar: false,
  },
  {
    key: "new-command",
    href: "/dashboard/commands/new",
    labelKey: "newCommand",
    aliases: ["create command", "script"],
    icon: Plus,
    section: "dashboard",
    sidebar: false,
  },
  {
    key: "new-run",
    href: "/ai/drafts/new",
    labelKey: "newRun",
    aliases: ["start run", "draft"],
    icon: PlayCircle,
    section: "ai",
    sidebar: false,
  },
  {
    key: "enroll-device",
    href: "/system/devices/enroll",
    labelKey: "enrollDevice",
    aliases: ["add device", "register device"],
    icon: UserPlus,
    section: "system",
    sidebar: false,
  },
  {
    key: "skill-groups",
    href: "/ai/skills/groups",
    labelKey: "skillGroups",
    aliases: ["groups"],
    icon: Sparkles,
    section: "ai",
    sidebar: false,
  },
];

export function destinationVisible(
  destination: AppDestination,
  features: NavigationFeatures,
): boolean {
  const required = [
    ...(destination.feature ? [destination.feature] : []),
    ...(destination.features ?? []),
  ];
  return required.every((feature) => features[feature]);
}

export function destinationActive(
  destination: AppDestination,
  pathname: string,
): boolean {
  if (destination.exact) return pathname === destination.href;
  const prefixes = destination.activePrefixes ?? [destination.href];
  return prefixes.some(
    (prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
  );
}
