UPDATE "GitHubApiCallLog"
SET "requestSource" = CASE "requestSource"
  WHEN 'GITHUB_APP_AUTHENTICATION' THEN 'GITHUB_SETTINGS'
  WHEN 'PULL_REQUESTS' THEN 'PULL_REQUESTS_PAGE'
  WHEN 'GITHUB_ACTIONS' THEN 'ACTIONS_PAGE'
  ELSE "requestSource"
END;
