import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const schemaPath = join(process.cwd(), "prisma", "schema.prisma");
const outputPath = join(
  process.cwd(),
  "src",
  "generated",
  "database-provider.ts",
);
const supportedProviders = ["sqlite", "postgresql"] as const;

const schema = readFileSync(schemaPath, "utf-8");
const datasource = schema.match(/\bdatasource\s+\w+\s*\{([\s\S]*?)\}/u)?.[1];
const provider = datasource?.match(/\bprovider\s*=\s*"([^"]+)"/u)?.[1];

if (
  !provider ||
  !supportedProviders.includes(provider as (typeof supportedProviders)[number])
) {
  throw new Error(
    `Expected ${schemaPath} to declare a supported datasource provider (${supportedProviders.join(
      ", ",
    )}).`,
  );
}

const generated = `// This file is auto-generated by scripts/prebuild-prisma.ts
// Do not edit manually

export type DatabaseProvider = "sqlite" | "postgresql";

export const databaseProvider = "${provider}" as const satisfies DatabaseProvider;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, generated, "utf-8");
console.log(`Generated ${outputPath} for the ${provider} provider.`);
