import {
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { extname, join } from "node:path";

// Bundles every schemas/**/*.graphql SDL file into a single generated TypeScript module
// (src/generated/schema-definitions.ts). Importing SDL as strings rather than reading the
// filesystem at runtime keeps the schema available inside the Next.js `standalone` bundle
// that the Homebrew service runs.

interface GraphQLFile {
  path: string;
  content: string;
}

function collectGraphQLFiles(dir: string, basePath = ""): GraphQLFile[] {
  const files: GraphQLFile[] = [];

  for (const item of readdirSync(dir)) {
    const fullPath = join(dir, item);
    const relativePath = basePath ? join(basePath, item) : item;

    if (statSync(fullPath).isDirectory()) {
      files.push(...collectGraphQLFiles(fullPath, relativePath));
    } else if (extname(item) === ".graphql") {
      files.push({
        path: relativePath,
        content: readFileSync(fullPath, "utf-8").trim(),
      });
    }
  }

  return files;
}

function generateSchemaFile(): void {
  const schemasDir = join(process.cwd(), "schemas");
  const outputDir = join(process.cwd(), "src", "generated");
  const outputPath = join(outputDir, "schema-definitions.ts");

  const graphqlFiles = collectGraphQLFiles(schemasDir);
  // Escape template-literal metacharacters so the SDL survives round-tripping into a `...`
  // string. Backslashes must be escaped first, otherwise GraphQL escapes like \" (used in
  // descriptions) get collapsed by the template literal and corrupt the schema.
  const escape = (content: string) =>
    content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

  const tsContent = `// This file is auto-generated by scripts/prebuild-schema.ts
// Do not edit manually

export const schemaDefinitions = [
${graphqlFiles.map((file) => `  \`${escape(file.content)}\``).join(",\n")}
];
`;

  mkdirSync(outputDir, { recursive: true });
  writeFileSync(outputPath, tsContent, "utf-8");
  console.log(
    `Generated ${outputPath} from ${graphqlFiles.length} schema file(s).`,
  );
}

generateSchemaFile();
